Update scripts

diff --git a/bin/kdeconnect-send-files b/bin/kdeconnect-send-files
--- a/bin/kdeconnect-send-files
+++ b/bin/kdeconnect-send-files
@@ -2,16 +2,28 @@
 
 filelist=~/.config/vifm/vimfiles
 name="Redmi 7A"
+notification_name="KDEConnect Send Files"
 
 st -c floating-st -g 120x30 -e vifm -f \
     -c "only" -c "set nodotfiles" -c "normal! gg" -c "set vifminfo="  \
     -c "set statusline='Select files to send via kdeconnect'" ~
 
+filecount="$(wc -l "$filelist" | cut -f1 -d' ')"
+failcount=0
+
 while read line; do
-    kdeconnect-cli -n "$name" --share "$line" ||
-        ( notify-send "KDEConnect file send" "KDEConnect failed to send the file(s)";  exit 1 )
-    # TODO: Make sleep change with file size
+    if ! kdeconnect-cli -n "$name" --share "$line"; then
+        failcount="$((failcount + 1))"
+    fi
+    # TODO: Make sleep change with file size, otherwise it sends it all almost
+    # at once and some downloads might fail
     sleep 3
 done < "$filelist"
 
-notify-send "KDEConnect file send" "Sent $(wc -l "$filelist" | cut -f1 -d' ') files"
+if [ "$failcount" -eq 0 ]; then
+    notify-send "$notification_name" "Sent $filecount files"
+elif [ "$failcount" -eq "$filecount" ]; then
+    notify-send "$notification_name" "Failed to send all files"
+else
+    notify-send "$notification_name" "Sent $((filecount - failcount)) files, $failcount failed"
+fi
